```{cat, engine.opts = list(file = "color.lua")}
Span = function(span)
  color = span.attributes['color']
  -- if no color attribute, return unchange
  if color == nil then return span end
  
  -- tranform to <span style="color: red;"></span>
  if FORMAT:match 'html' then
    -- remove color attributes
    span.attributes['color'] = nil
    -- use style attribute instead
    span.attributes['style'] = 'color: ' .. color .. ';'
    -- return full span element
    return span
  elseif FORMAT:match 'latex' then
    -- remove color attributes
    span.attributes['color'] = nil
    -- encapsulate in latex code
    table.insert(
      span.content, 1,
      pandoc.RawInline('latex', '\\textcolor{'..color..'}{')
    )
    table.insert(
      span.content,
      pandoc.RawInline('latex', '}')
    )
    -- returns only span content
    return span.content
  else
    -- for other format return unchanged
    return span
  end
end
```

```{js, echo=FALSE}
function toggleTOC(){
$("#TOC").toggle()
}

$(document).mouseup(function (e) {
    var div1 = $("#TOC");
    var div2 = $("#toc-controls");
    if ($(e.target).closest(div2).length)
    {
       idiv2.toggle();
     }
    if (!$(e.target).closest(div1).length)
    {
       div1.hide();
     }
    });
```

<!--- 
\iffalse
--->

::: {#toc-controls}
<button type="button" id="toc-toggle" class="btn-link btn-xs" onclick="toggleTOC()">
<span class="glyphicon glyphicon-menu-hamburger" data-toggle="collapse" style="font-size:20px"></span>
</button>
:::

<!--- 
\fi
--->

```{css, echo=FALSE}

/*-------------------------------------------------------------------------------*/
/* TOC */  
  
#TOC::before {
  content: "Contents";
  font-variant: small-caps;
  font-family: Arial, Helvetica, sans-serif;
  text-align: center;
  display: block;
  position: -webkit-sticky; /* Safari */
  position: sticky;
  top: 0;
  height: 38px;
  color: red;
}

div.tocify {
width: 18%;
max-width: 20%;
max-height:92vh;
}

#TOC{
position:fixed;
top:8px;
right:0;
margin: 25px 5px 0px 0px;
z-index:2;
display:none;
opacity:1;
word-wrap: break-word;
background-color:  #ffffff;
padding: 10px;
font-size: 75%;
font-family: Arial, Helvetica, sans-serif;
font-weight: 200;
border: none;
/* border: solid 1px; */
box-shadow:  0 3px 6px rgba(0,0,0,0.16), 0 4px 6px rgba(0,0,0,0.45);
/* border-radius: 10px;*/
}

#toc-controls{
position:fixed;
top:0;
right:1px;
margin:0;
opacity: 0.4;
}

.col-md-3{
width: 0%
}

.col-md-9{
width: 100%
}

/*-------------------------------------------------------------------------------*/

img {
  margin-left: auto;
  margin-right: auto;
  padding-top: 10px;
  padding-bottom: 10px; 
}

pre {
  white-space: pre !important;
  overflow-y: auto!important;
  overflow-x:auto !important;
  max-height: 300px !important;
}

pre.r {
  max-height: none;
}

pre, code {white-space:pre !important; overflow-x:auto !important}


/*-------------------------------------------------------------------------------*/
/* https://www.w3schools.com/tags/tag_summary.asp */
/* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details */  
  
details > summary {
  #text-align: right;
  width: 100%;
  font-size: 80%;
  font-weight: bold;
  margin-top: -1em;
  margin-bottom: 0em;
  color: #4e89bf;
  font-variant: small-caps;
  #display:none;
  #visibility: hidden;
  cursor: pointer;
}

/*-------------------------------------------------------------------------------*/
/* https://flickity.metafizzy.co/ */

.gallery-cell {
  width: 100%;
  margin-right: 10px;
  counter-increment: gallery-cell;
}

.flickity-button {
   opacity: 0.5;
}

.flickity-prev-next-button.previous {
  left: -40px;
}
.flickity-prev-next-button.next {
  right: -40px;
}

.flickity-page-dots {
  bottom: 0px;
}


/*-------------------------------------------------------------------------------*/
/* https://css-tricks.com/can-get-pretty-far-making-slider-just-html-css/ */

.slider {
  width: 100%;
  height: auto;
  display: flex;
  overflow-x: auto;
  scroll-snap-points-x: repeat(300px);
  scroll-snap-type: mandatory;
}

.slider > div {
  width: 100%;
  flex-shrink: 0;
  height: 100%;
  scroll-snap-align: start;
}


```


<!--- https://bookdown.org/yihui/rmarkdown-cookbook/eng-cat.html --->

```{cat, engine.opts = list(file = "sol.css")}
/* ----------------------------- */
```



```{cat, engine.opts = list(file = "sol.css"), eval=params$sol=="false"}
.sol {display: none;}
/* details.sol {display: none;} */
```

<!---  https://bookdown.org/yihui/rmarkdown-cookbook/raw-latex.html --->

```{=latex}
\newif\ifsol
\sol`r params$sol`
\excludecomment{sol}  %  LaTex package "comment" needed
\ifsol
\includecomment{sol}
\fi
```

```{r, include=FALSE}

require(knitr)
require(kableExtra)
require(formatR)

require(latex2exp)

require(ggplot2)
require(rgl)

#require(broom)
#require(patchwork)
xaringanExtra::use_panelset()
xaringanExtra::use_clipboard(button_text = "Copy")
# klippy::klippy(lang = c("r", "md", "yaml", "markdown"), position = c("top", "right"))

#--------------------------------------------------

#knitr hook function to allow an fold option
# Folding code |---> fold="title"

hooks <- knit_hooks$get("chunk")
knit_hooks$set(chunk = function(x, options) {
  res <- hooks(x, options)
  if (!is.null(options$fold)) {
    paste0(
      "<details><summary>", options$fold, "</summary>\n\n",
      res,
      "\n\n</details>"
    )
  } else {
    return(res)
  }
})

#----------------------------------------

# knitr hook function to allow an output.lines option
# e.g.,
#   "output.lines=n" prints lines 1:n ...
#   "output.lines=1:n" does the same
#   "output.lines=3:15" prints lines ... 3:15 ...
#   "output.lines=-(1:8)" removes lines 1:8 and prints ... 9:n ...
#   No allowance for anything but a consecutive range of lines

hook_output <- knit_hooks$get("output")
knit_hooks$set(output = function(x, options) {
  lines <- options$output.lines
  if (is.null(lines)) {
    return(hook_output(x, options)) # pass to default hook
  }
  x <- unlist(strsplit(x, "\n"))
  if (length(lines) == 1) { # first n lines
    if (length(x) > lines) {x <- head(x, lines)}
  } else {x <- x[lines]}
  # paste these lines together
  x <- paste(c(x, ""), collapse = "\n")
  hook_output(x, options)
})

#----------------------------------------

opts_chunk$set( # https://yihui.name/knitr/options
  # eval = TRUE,
  # echo = FALSE,
  # cache = FALSE,
  # results = 'hold',
  # collapse = FALSE,
  comment = NA, # comment="",
  prompt = FALSE,
  # tidy = "styler", # https://styler.r-lib.org/
  tidy = TRUE,
  tidy.opts = list(arrow = TRUE, indent = 2, width.cutoff = ifelse(is_latex_output(),65,150)),
  fig.align = "center",
  fig.width = 9,
  fig.asp = 0.618,
  #fig.height = 4,
  out.width = "80%",
  dev = if(is_html_output()) {"svg"},
  fig.pos = "H",
  out.extra = ""
)

options(digits = 3, 
        scipen = 0
        )

opts_knit$set(global.par = TRUE)
```

```{r, include=FALSE}
par(mar = c(4, 4, .1, .1))
```


```{r, include=FALSE}
# ggplot----------------------------------------------------
# theme_set(theme_minimal())
my_them <- theme_grey() + theme_bw() +
    theme(
      strip.text = element_text(face = "bold", size = 12, margin = margin()),
      legend.title = element_text(face = "bold", size = 10),
      legend.position="top",
      legend.text = element_text(face = "bold", size = 10),
      plot.title = element_text(face = "bold", size = 14),
      axis.title.x = element_text(face = "bold", size = 10),
      axis.title.y = element_text(face = "bold", size = 10),
      axis.text.x = element_text(face = "bold", size = 10),
      axis.text.y = element_text(face = "bold", size = 10),
      axis.line.x = element_line(color = "black", size = 0.5),
      axis.line.y = element_line(color = "black", size = 0.5)
    )

theme_set(my_them)

```


```{r, include=FALSE}
# 3d plots : rgl package ----------------------------------------
options(rgl.useNULL=TRUE)
hook_webgl <- local({
  commonParts <- TRUE
  reuse <- TRUE
  function (before, options, envir) 
  {
    if (before || rgl::rgl.cur() == 0 || !requireNamespace("knitr")) 
      return()
    out_type <- knitr::opts_knit$get("out.format")
    if (!length(intersect(out_type, c("markdown", "html"))))       
      stop("hook_webgl is for HTML only.  Use knitr::hook_rgl instead.")
    
    name <- tempfile("webgl", tmpdir = ".", fileext = ".html")
    on.exit(unlink(name))
    dpi <- 96 # was options$dpi
    rgl::par3d(windowRect = dpi * c(0, 0, options$fig.width, 
                                            options$fig.height))
    Sys.sleep(0.1)
    prefix = gsub("[^[:alnum:]]", "_", options$label)
    prefix = sub("^([^[:alpha:]])", "_\\1", prefix)
    res <- rgl::writeWebGL(dir = dirname(name), 
                    filename = name, 
                    snapshot = !rgl.useNULL(),
                    template = NULL, 
                    prefix = prefix, 
                    commonParts = commonParts,
                    reuse = reuse)
    if (!isTRUE(options$rgl.keepopen) && rgl.cur())
      rgl.close()
    commonParts <<- FALSE
    reuse <<- attr(res, "reuse")
    res <- readLines(name)
    res <- res[!grepl("^\\s*$", res)]
    paste(gsub("^\\s+", "", res), collapse = "\n")
  }
})

knit_hooks$set(rgl = hook_webgl)
```

```{r, include=FALSE}
# knitr::knit_exit()
```

